galaxy_info:
  role_name: jenkins
  author: rpytel
  description: Jenkins install and configuration role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: docker
